---
apiVersion: v1
kind: BuildConfig
metadata:
  name: forest-mnist-train-gpu
  annotations:
    description: >
      Source-to-Image (S2I) builder image for training a TF model
  labels:
    component: training
spec:
  output:
    to:
      kind: ImageStreamTag
      name: forest-mnist-train:gpu
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://gitlab.com/vpavlin/hybrid-data-engineering-workshop.git
      ref: tf-job
    contextDir: source/tf-random-forest/train
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-36-ubi7:10.0-cudnn7-devel-ubi7
    type: Source
  triggers:
    - type: ConfigChange
status:
  lastVersion: 0
---
kind: ImageStream
apiVersion: v1
metadata:
  name: forest-mnist-train
  labels:
    component: training
spec:
  lookupPolicy:
    local: true